version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: marknadsplatsen_postgres
    environment:
      POSTGRES_DB: marknadsplatsen
      POSTGRES_USER: marknadsplatsen_all_access
      POSTGRES_PASSWORD: strong_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
